on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x, 14.x]

        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
                  registry-url: https://registry.npmjs.org/

            - name: Install
              run: yarn install

            - name: Build
              run: yarn build

            - name: Test
              run: yarn test

            - run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
