name: Release

on:
    push:
        tags:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - name: Install
              run: yarn install

            - name: Build
              run: yarn build
